version: "3"

services:
  gemini-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./main.py:/app/main.py
      - ./pyproject.toml:/app/pyproject.toml
      - ./.proxy_secret:/app/.proxy_secret
    env_file:
      - .env
    restart: unless-stopped
